// flow-typed signature: 59e5f6ea4985759fc096673672769bef
// flow-typed version: <<STUB>>/puppeteer_v7.1/flow_v0.145.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'puppeteer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'puppeteer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'puppeteer/cjs-entry-core' {
  declare module.exports: any;
}

declare module 'puppeteer/cjs-entry' {
  declare module.exports: any;
}

declare module 'puppeteer/install' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/api-docs-entry' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/common/Accessibility' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/common/AriaQueryHandler' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/common/assert' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/common/Browser' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/common/BrowserConnector' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/common/BrowserWebSocketTransport' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/common/Connection' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/common/ConnectionTransport' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/common/ConsoleMessage' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/common/Coverage' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/common/Debug' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/common/DeviceDescriptors' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/common/Dialog' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/common/DOMWorld' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/common/EmulationManager' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/common/Errors' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/common/EvalTypes' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/common/EventEmitter' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/common/Events' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/common/ExecutionContext' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/common/fetch' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/common/FileChooser' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/common/FrameManager' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/common/helper' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/common/HTTPRequest' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/common/HTTPResponse' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/common/Input' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/common/JSHandle' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/common/NetworkConditions' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/common/NetworkManager' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/common/Page' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/common/PDFOptions' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/common/Product' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/common/Puppeteer' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/common/PuppeteerViewport' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/common/QueryHandler' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/common/SecurityDetails' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/common/Target' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/common/TimeoutSettings' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/common/Tracing' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/common/USKeyboardLayout' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/common/WebWorker' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/environment' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/initialize-node' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/initialize-web' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/node-puppeteer-core' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/node' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/node/BrowserFetcher' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/node/BrowserRunner' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/node/install' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/node/Launcher' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/node/LaunchOptions' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/node/NodeWebSocketTransport' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/node/PipeTransport' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/node/Puppeteer' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/revisions' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/puppeteer/web' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/cjs/vendor/mitt/src' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/api-docs-entry' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/common/Accessibility' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/common/AriaQueryHandler' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/common/assert' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/common/Browser' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/common/BrowserConnector' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/common/BrowserWebSocketTransport' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/common/Connection' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/common/ConnectionTransport' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/common/ConsoleMessage' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/common/Coverage' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/common/Debug' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/common/DeviceDescriptors' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/common/Dialog' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/common/DOMWorld' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/common/EmulationManager' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/common/Errors' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/common/EvalTypes' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/common/EventEmitter' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/common/Events' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/common/ExecutionContext' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/common/fetch' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/common/FileChooser' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/common/FrameManager' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/common/helper' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/common/HTTPRequest' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/common/HTTPResponse' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/common/Input' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/common/JSHandle' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/common/LifecycleWatcher' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/common/NetworkConditions' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/common/NetworkManager' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/common/Page' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/common/PDFOptions' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/common/Product' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/common/Puppeteer' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/common/PuppeteerViewport' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/common/QueryHandler' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/common/SecurityDetails' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/common/Target' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/common/TimeoutSettings' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/common/Tracing' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/common/USKeyboardLayout' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/common/WebWorker' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/environment' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/initialize-node' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/initialize-web' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/node-puppeteer-core' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/node' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/node/BrowserFetcher' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/node/BrowserRunner' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/node/install' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/node/Launcher' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/node/LaunchOptions' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/node/NodeWebSocketTransport' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/node/PipeTransport' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/node/Puppeteer' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/revisions' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/puppeteer/web' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/esm/vendor/mitt/src' {
  declare module.exports: any;
}

declare module 'puppeteer/typescript-if-required' {
  declare module.exports: any;
}

// Filename aliases
declare module 'puppeteer/cjs-entry-core.js' {
  declare module.exports: $Exports<'puppeteer/cjs-entry-core'>;
}
declare module 'puppeteer/cjs-entry.js' {
  declare module.exports: $Exports<'puppeteer/cjs-entry'>;
}
declare module 'puppeteer/install.js' {
  declare module.exports: $Exports<'puppeteer/install'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/api-docs-entry.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/api-docs-entry'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/common/Accessibility.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/common/Accessibility'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/common/AriaQueryHandler.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/common/AriaQueryHandler'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/common/assert.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/common/assert'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/common/Browser.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/common/Browser'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/common/BrowserConnector.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/common/BrowserConnector'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/common/BrowserWebSocketTransport.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/common/BrowserWebSocketTransport'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/common/Connection.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/common/Connection'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/common/ConnectionTransport.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/common/ConnectionTransport'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/common/ConsoleMessage.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/common/ConsoleMessage'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/common/Coverage.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/common/Coverage'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/common/Debug.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/common/Debug'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/common/DeviceDescriptors.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/common/DeviceDescriptors'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/common/Dialog.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/common/Dialog'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/common/DOMWorld.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/common/DOMWorld'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/common/EmulationManager.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/common/EmulationManager'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/common/Errors.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/common/Errors'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/common/EvalTypes.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/common/EvalTypes'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/common/EventEmitter.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/common/EventEmitter'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/common/Events.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/common/Events'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/common/ExecutionContext'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/common/fetch.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/common/fetch'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/common/FileChooser.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/common/FileChooser'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/common/FrameManager.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/common/FrameManager'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/common/helper.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/common/helper'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/common/HTTPRequest.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/common/HTTPRequest'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/common/HTTPResponse.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/common/HTTPResponse'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/common/Input.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/common/Input'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/common/JSHandle.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/common/JSHandle'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/common/NetworkConditions.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/common/NetworkConditions'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/common/NetworkManager.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/common/NetworkManager'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/common/Page.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/common/Page'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/common/PDFOptions.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/common/PDFOptions'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/common/Product.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/common/Product'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/common/Puppeteer.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/common/Puppeteer'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/common/PuppeteerViewport.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/common/PuppeteerViewport'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/common/QueryHandler.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/common/QueryHandler'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/common/SecurityDetails.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/common/SecurityDetails'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/common/Target.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/common/Target'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/common/TimeoutSettings.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/common/TimeoutSettings'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/common/Tracing.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/common/Tracing'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/common/USKeyboardLayout.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/common/USKeyboardLayout'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/common/WebWorker.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/common/WebWorker'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/environment.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/environment'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/initialize-node.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/initialize-node'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/initialize-web.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/initialize-web'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/node-puppeteer-core.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/node-puppeteer-core'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/node.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/node'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/node/BrowserFetcher'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/node/BrowserRunner'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/node/install.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/node/install'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/node/Launcher.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/node/Launcher'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/node/LaunchOptions.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/node/LaunchOptions'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/node/NodeWebSocketTransport.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/node/NodeWebSocketTransport'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/node/PipeTransport.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/node/PipeTransport'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/node/Puppeteer.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/node/Puppeteer'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/revisions.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/revisions'>;
}
declare module 'puppeteer/lib/cjs/puppeteer/web.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/puppeteer/web'>;
}
declare module 'puppeteer/lib/cjs/vendor/mitt/src/index' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/vendor/mitt/src'>;
}
declare module 'puppeteer/lib/cjs/vendor/mitt/src/index.js' {
  declare module.exports: $Exports<'puppeteer/lib/cjs/vendor/mitt/src'>;
}
declare module 'puppeteer/lib/esm/puppeteer/api-docs-entry.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/api-docs-entry'>;
}
declare module 'puppeteer/lib/esm/puppeteer/common/Accessibility.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/common/Accessibility'>;
}
declare module 'puppeteer/lib/esm/puppeteer/common/AriaQueryHandler.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/common/AriaQueryHandler'>;
}
declare module 'puppeteer/lib/esm/puppeteer/common/assert.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/common/assert'>;
}
declare module 'puppeteer/lib/esm/puppeteer/common/Browser.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/common/Browser'>;
}
declare module 'puppeteer/lib/esm/puppeteer/common/BrowserConnector.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/common/BrowserConnector'>;
}
declare module 'puppeteer/lib/esm/puppeteer/common/BrowserWebSocketTransport.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/common/BrowserWebSocketTransport'>;
}
declare module 'puppeteer/lib/esm/puppeteer/common/Connection.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/common/Connection'>;
}
declare module 'puppeteer/lib/esm/puppeteer/common/ConnectionTransport.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/common/ConnectionTransport'>;
}
declare module 'puppeteer/lib/esm/puppeteer/common/ConsoleMessage.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/common/ConsoleMessage'>;
}
declare module 'puppeteer/lib/esm/puppeteer/common/Coverage.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/common/Coverage'>;
}
declare module 'puppeteer/lib/esm/puppeteer/common/Debug.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/common/Debug'>;
}
declare module 'puppeteer/lib/esm/puppeteer/common/DeviceDescriptors.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/common/DeviceDescriptors'>;
}
declare module 'puppeteer/lib/esm/puppeteer/common/Dialog.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/common/Dialog'>;
}
declare module 'puppeteer/lib/esm/puppeteer/common/DOMWorld.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/common/DOMWorld'>;
}
declare module 'puppeteer/lib/esm/puppeteer/common/EmulationManager.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/common/EmulationManager'>;
}
declare module 'puppeteer/lib/esm/puppeteer/common/Errors.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/common/Errors'>;
}
declare module 'puppeteer/lib/esm/puppeteer/common/EvalTypes.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/common/EvalTypes'>;
}
declare module 'puppeteer/lib/esm/puppeteer/common/EventEmitter.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/common/EventEmitter'>;
}
declare module 'puppeteer/lib/esm/puppeteer/common/Events.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/common/Events'>;
}
declare module 'puppeteer/lib/esm/puppeteer/common/ExecutionContext.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/common/ExecutionContext'>;
}
declare module 'puppeteer/lib/esm/puppeteer/common/fetch.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/common/fetch'>;
}
declare module 'puppeteer/lib/esm/puppeteer/common/FileChooser.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/common/FileChooser'>;
}
declare module 'puppeteer/lib/esm/puppeteer/common/FrameManager.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/common/FrameManager'>;
}
declare module 'puppeteer/lib/esm/puppeteer/common/helper.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/common/helper'>;
}
declare module 'puppeteer/lib/esm/puppeteer/common/HTTPRequest.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/common/HTTPRequest'>;
}
declare module 'puppeteer/lib/esm/puppeteer/common/HTTPResponse.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/common/HTTPResponse'>;
}
declare module 'puppeteer/lib/esm/puppeteer/common/Input.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/common/Input'>;
}
declare module 'puppeteer/lib/esm/puppeteer/common/JSHandle.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/common/JSHandle'>;
}
declare module 'puppeteer/lib/esm/puppeteer/common/LifecycleWatcher.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/common/LifecycleWatcher'>;
}
declare module 'puppeteer/lib/esm/puppeteer/common/NetworkConditions.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/common/NetworkConditions'>;
}
declare module 'puppeteer/lib/esm/puppeteer/common/NetworkManager.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/common/NetworkManager'>;
}
declare module 'puppeteer/lib/esm/puppeteer/common/Page.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/common/Page'>;
}
declare module 'puppeteer/lib/esm/puppeteer/common/PDFOptions.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/common/PDFOptions'>;
}
declare module 'puppeteer/lib/esm/puppeteer/common/Product.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/common/Product'>;
}
declare module 'puppeteer/lib/esm/puppeteer/common/Puppeteer.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/common/Puppeteer'>;
}
declare module 'puppeteer/lib/esm/puppeteer/common/PuppeteerViewport.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/common/PuppeteerViewport'>;
}
declare module 'puppeteer/lib/esm/puppeteer/common/QueryHandler.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/common/QueryHandler'>;
}
declare module 'puppeteer/lib/esm/puppeteer/common/SecurityDetails.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/common/SecurityDetails'>;
}
declare module 'puppeteer/lib/esm/puppeteer/common/Target.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/common/Target'>;
}
declare module 'puppeteer/lib/esm/puppeteer/common/TimeoutSettings.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/common/TimeoutSettings'>;
}
declare module 'puppeteer/lib/esm/puppeteer/common/Tracing.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/common/Tracing'>;
}
declare module 'puppeteer/lib/esm/puppeteer/common/USKeyboardLayout.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/common/USKeyboardLayout'>;
}
declare module 'puppeteer/lib/esm/puppeteer/common/WebWorker.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/common/WebWorker'>;
}
declare module 'puppeteer/lib/esm/puppeteer/environment.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/environment'>;
}
declare module 'puppeteer/lib/esm/puppeteer/initialize-node.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/initialize-node'>;
}
declare module 'puppeteer/lib/esm/puppeteer/initialize-web.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/initialize-web'>;
}
declare module 'puppeteer/lib/esm/puppeteer/node-puppeteer-core.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/node-puppeteer-core'>;
}
declare module 'puppeteer/lib/esm/puppeteer/node.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/node'>;
}
declare module 'puppeteer/lib/esm/puppeteer/node/BrowserFetcher.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/node/BrowserFetcher'>;
}
declare module 'puppeteer/lib/esm/puppeteer/node/BrowserRunner.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/node/BrowserRunner'>;
}
declare module 'puppeteer/lib/esm/puppeteer/node/install.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/node/install'>;
}
declare module 'puppeteer/lib/esm/puppeteer/node/Launcher.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/node/Launcher'>;
}
declare module 'puppeteer/lib/esm/puppeteer/node/LaunchOptions.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/node/LaunchOptions'>;
}
declare module 'puppeteer/lib/esm/puppeteer/node/NodeWebSocketTransport.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/node/NodeWebSocketTransport'>;
}
declare module 'puppeteer/lib/esm/puppeteer/node/PipeTransport.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/node/PipeTransport'>;
}
declare module 'puppeteer/lib/esm/puppeteer/node/Puppeteer.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/node/Puppeteer'>;
}
declare module 'puppeteer/lib/esm/puppeteer/revisions.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/revisions'>;
}
declare module 'puppeteer/lib/esm/puppeteer/web.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/puppeteer/web'>;
}
declare module 'puppeteer/lib/esm/vendor/mitt/src/index' {
  declare module.exports: $Exports<'puppeteer/lib/esm/vendor/mitt/src'>;
}
declare module 'puppeteer/lib/esm/vendor/mitt/src/index.js' {
  declare module.exports: $Exports<'puppeteer/lib/esm/vendor/mitt/src'>;
}
declare module 'puppeteer/typescript-if-required.js' {
  declare module.exports: $Exports<'puppeteer/typescript-if-required'>;
}
