// flow-typed signature: 9570a670c171107c8469bedc0382de14
// flow-typed version: <<STUB>>/crc_v^3.8.0/flow_v0.145.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'crc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'crc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'crc/crc1' {
  declare module.exports: any;
}

declare module 'crc/crc16' {
  declare module.exports: any;
}

declare module 'crc/crc16ccitt' {
  declare module.exports: any;
}

declare module 'crc/crc16kermit' {
  declare module.exports: any;
}

declare module 'crc/crc16modbus' {
  declare module.exports: any;
}

declare module 'crc/crc16xmodem' {
  declare module.exports: any;
}

declare module 'crc/crc17ccitt' {
  declare module.exports: any;
}

declare module 'crc/crc17kermit' {
  declare module.exports: any;
}

declare module 'crc/crc17modbus' {
  declare module.exports: any;
}

declare module 'crc/crc17xmodem' {
  declare module.exports: any;
}

declare module 'crc/crc24' {
  declare module.exports: any;
}

declare module 'crc/crc32' {
  declare module.exports: any;
}

declare module 'crc/crc8' {
  declare module.exports: any;
}

declare module 'crc/crc81wire' {
  declare module.exports: any;
}

declare module 'crc/crc91wire' {
  declare module.exports: any;
}

declare module 'crc/crcjam' {
  declare module.exports: any;
}

declare module 'crc/create_buffer' {
  declare module.exports: any;
}

declare module 'crc/define_crc' {
  declare module.exports: any;
}

declare module 'crc/lib/crc1' {
  declare module.exports: any;
}

declare module 'crc/lib/crc16_ccitt' {
  declare module.exports: any;
}

declare module 'crc/lib/crc16_kermit' {
  declare module.exports: any;
}

declare module 'crc/lib/crc16_modbus' {
  declare module.exports: any;
}

declare module 'crc/lib/crc16_xmodem' {
  declare module.exports: any;
}

declare module 'crc/lib/crc16' {
  declare module.exports: any;
}

declare module 'crc/lib/crc17_ccitt' {
  declare module.exports: any;
}

declare module 'crc/lib/crc17_kermit' {
  declare module.exports: any;
}

declare module 'crc/lib/crc17_modbus' {
  declare module.exports: any;
}

declare module 'crc/lib/crc17_xmodem' {
  declare module.exports: any;
}

declare module 'crc/lib/crc24' {
  declare module.exports: any;
}

declare module 'crc/lib/crc32' {
  declare module.exports: any;
}

declare module 'crc/lib/crc8_1wire' {
  declare module.exports: any;
}

declare module 'crc/lib/crc8' {
  declare module.exports: any;
}

declare module 'crc/lib/crc9_1wire' {
  declare module.exports: any;
}

declare module 'crc/lib/crcjam' {
  declare module.exports: any;
}

declare module 'crc/lib/es6/crc1' {
  declare module.exports: any;
}

declare module 'crc/lib/es6/crc16' {
  declare module.exports: any;
}

declare module 'crc/lib/es6/crc16ccitt' {
  declare module.exports: any;
}

declare module 'crc/lib/es6/crc16kermit' {
  declare module.exports: any;
}

declare module 'crc/lib/es6/crc16modbus' {
  declare module.exports: any;
}

declare module 'crc/lib/es6/crc16xmodem' {
  declare module.exports: any;
}

declare module 'crc/lib/es6/crc17ccitt' {
  declare module.exports: any;
}

declare module 'crc/lib/es6/crc17kermit' {
  declare module.exports: any;
}

declare module 'crc/lib/es6/crc17modbus' {
  declare module.exports: any;
}

declare module 'crc/lib/es6/crc17xmodem' {
  declare module.exports: any;
}

declare module 'crc/lib/es6/crc24' {
  declare module.exports: any;
}

declare module 'crc/lib/es6/crc32' {
  declare module.exports: any;
}

declare module 'crc/lib/es6/crc8' {
  declare module.exports: any;
}

declare module 'crc/lib/es6/crc81wire' {
  declare module.exports: any;
}

declare module 'crc/lib/es6/crc91wire' {
  declare module.exports: any;
}

declare module 'crc/lib/es6/crcjam' {
  declare module.exports: any;
}

declare module 'crc/lib/es6/create_buffer' {
  declare module.exports: any;
}

declare module 'crc/lib/es6/define_crc' {
  declare module.exports: any;
}

declare module 'crc/lib/es6' {
  declare module.exports: any;
}

declare module 'crc/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'crc/crc1.js' {
  declare module.exports: $Exports<'crc/crc1'>;
}
declare module 'crc/crc16.js' {
  declare module.exports: $Exports<'crc/crc16'>;
}
declare module 'crc/crc16ccitt.js' {
  declare module.exports: $Exports<'crc/crc16ccitt'>;
}
declare module 'crc/crc16kermit.js' {
  declare module.exports: $Exports<'crc/crc16kermit'>;
}
declare module 'crc/crc16modbus.js' {
  declare module.exports: $Exports<'crc/crc16modbus'>;
}
declare module 'crc/crc16xmodem.js' {
  declare module.exports: $Exports<'crc/crc16xmodem'>;
}
declare module 'crc/crc17ccitt.js' {
  declare module.exports: $Exports<'crc/crc17ccitt'>;
}
declare module 'crc/crc17kermit.js' {
  declare module.exports: $Exports<'crc/crc17kermit'>;
}
declare module 'crc/crc17modbus.js' {
  declare module.exports: $Exports<'crc/crc17modbus'>;
}
declare module 'crc/crc17xmodem.js' {
  declare module.exports: $Exports<'crc/crc17xmodem'>;
}
declare module 'crc/crc24.js' {
  declare module.exports: $Exports<'crc/crc24'>;
}
declare module 'crc/crc32.js' {
  declare module.exports: $Exports<'crc/crc32'>;
}
declare module 'crc/crc8.js' {
  declare module.exports: $Exports<'crc/crc8'>;
}
declare module 'crc/crc81wire.js' {
  declare module.exports: $Exports<'crc/crc81wire'>;
}
declare module 'crc/crc91wire.js' {
  declare module.exports: $Exports<'crc/crc91wire'>;
}
declare module 'crc/crcjam.js' {
  declare module.exports: $Exports<'crc/crcjam'>;
}
declare module 'crc/create_buffer.js' {
  declare module.exports: $Exports<'crc/create_buffer'>;
}
declare module 'crc/define_crc.js' {
  declare module.exports: $Exports<'crc/define_crc'>;
}
declare module 'crc/index' {
  declare module.exports: $Exports<'crc'>;
}
declare module 'crc/index.js' {
  declare module.exports: $Exports<'crc'>;
}
declare module 'crc/lib/crc1.js' {
  declare module.exports: $Exports<'crc/lib/crc1'>;
}
declare module 'crc/lib/crc16_ccitt.js' {
  declare module.exports: $Exports<'crc/lib/crc16_ccitt'>;
}
declare module 'crc/lib/crc16_kermit.js' {
  declare module.exports: $Exports<'crc/lib/crc16_kermit'>;
}
declare module 'crc/lib/crc16_modbus.js' {
  declare module.exports: $Exports<'crc/lib/crc16_modbus'>;
}
declare module 'crc/lib/crc16_xmodem.js' {
  declare module.exports: $Exports<'crc/lib/crc16_xmodem'>;
}
declare module 'crc/lib/crc16.js' {
  declare module.exports: $Exports<'crc/lib/crc16'>;
}
declare module 'crc/lib/crc17_ccitt.js' {
  declare module.exports: $Exports<'crc/lib/crc17_ccitt'>;
}
declare module 'crc/lib/crc17_kermit.js' {
  declare module.exports: $Exports<'crc/lib/crc17_kermit'>;
}
declare module 'crc/lib/crc17_modbus.js' {
  declare module.exports: $Exports<'crc/lib/crc17_modbus'>;
}
declare module 'crc/lib/crc17_xmodem.js' {
  declare module.exports: $Exports<'crc/lib/crc17_xmodem'>;
}
declare module 'crc/lib/crc24.js' {
  declare module.exports: $Exports<'crc/lib/crc24'>;
}
declare module 'crc/lib/crc32.js' {
  declare module.exports: $Exports<'crc/lib/crc32'>;
}
declare module 'crc/lib/crc8_1wire.js' {
  declare module.exports: $Exports<'crc/lib/crc8_1wire'>;
}
declare module 'crc/lib/crc8.js' {
  declare module.exports: $Exports<'crc/lib/crc8'>;
}
declare module 'crc/lib/crc9_1wire.js' {
  declare module.exports: $Exports<'crc/lib/crc9_1wire'>;
}
declare module 'crc/lib/crcjam.js' {
  declare module.exports: $Exports<'crc/lib/crcjam'>;
}
declare module 'crc/lib/es6/crc1.js' {
  declare module.exports: $Exports<'crc/lib/es6/crc1'>;
}
declare module 'crc/lib/es6/crc16.js' {
  declare module.exports: $Exports<'crc/lib/es6/crc16'>;
}
declare module 'crc/lib/es6/crc16ccitt.js' {
  declare module.exports: $Exports<'crc/lib/es6/crc16ccitt'>;
}
declare module 'crc/lib/es6/crc16kermit.js' {
  declare module.exports: $Exports<'crc/lib/es6/crc16kermit'>;
}
declare module 'crc/lib/es6/crc16modbus.js' {
  declare module.exports: $Exports<'crc/lib/es6/crc16modbus'>;
}
declare module 'crc/lib/es6/crc16xmodem.js' {
  declare module.exports: $Exports<'crc/lib/es6/crc16xmodem'>;
}
declare module 'crc/lib/es6/crc17ccitt.js' {
  declare module.exports: $Exports<'crc/lib/es6/crc17ccitt'>;
}
declare module 'crc/lib/es6/crc17kermit.js' {
  declare module.exports: $Exports<'crc/lib/es6/crc17kermit'>;
}
declare module 'crc/lib/es6/crc17modbus.js' {
  declare module.exports: $Exports<'crc/lib/es6/crc17modbus'>;
}
declare module 'crc/lib/es6/crc17xmodem.js' {
  declare module.exports: $Exports<'crc/lib/es6/crc17xmodem'>;
}
declare module 'crc/lib/es6/crc24.js' {
  declare module.exports: $Exports<'crc/lib/es6/crc24'>;
}
declare module 'crc/lib/es6/crc32.js' {
  declare module.exports: $Exports<'crc/lib/es6/crc32'>;
}
declare module 'crc/lib/es6/crc8.js' {
  declare module.exports: $Exports<'crc/lib/es6/crc8'>;
}
declare module 'crc/lib/es6/crc81wire.js' {
  declare module.exports: $Exports<'crc/lib/es6/crc81wire'>;
}
declare module 'crc/lib/es6/crc91wire.js' {
  declare module.exports: $Exports<'crc/lib/es6/crc91wire'>;
}
declare module 'crc/lib/es6/crcjam.js' {
  declare module.exports: $Exports<'crc/lib/es6/crcjam'>;
}
declare module 'crc/lib/es6/create_buffer.js' {
  declare module.exports: $Exports<'crc/lib/es6/create_buffer'>;
}
declare module 'crc/lib/es6/define_crc.js' {
  declare module.exports: $Exports<'crc/lib/es6/define_crc'>;
}
declare module 'crc/lib/es6/index' {
  declare module.exports: $Exports<'crc/lib/es6'>;
}
declare module 'crc/lib/es6/index.js' {
  declare module.exports: $Exports<'crc/lib/es6'>;
}
declare module 'crc/lib/index' {
  declare module.exports: $Exports<'crc/lib'>;
}
declare module 'crc/lib/index.js' {
  declare module.exports: $Exports<'crc/lib'>;
}
